/** Ticker → fund name lookup for the factor portfolio table. */
const ETF_NAMES: Record<string, string> = {
  QUAL: "iShares MSCI USA Quality Factor ETF",
  MTUM: "iShares MSCI USA Momentum Factor ETF",
  VLUE: "iShares MSCI USA Value Factor ETF",
  SIZE: "iShares MSCI USA Size Factor ETF",
  USMV: "iShares MSCI USA Min Vol Factor ETF",
  SPLV: "Invesco S&P 500 Low Volatility ETF",
  SPHQ: "Invesco S&P 500 Quality ETF",
  COWZ: "Pacer US Cash Cows 100 ETF",
  VTV: "Vanguard Value ETF",
  VUG: "Vanguard Growth ETF",
  VBR: "Vanguard Small-Cap Value ETF",
  VB: "Vanguard Small-Cap ETF",
  VOO: "Vanguard S&P 500 ETF",
  VTI: "Vanguard Total Stock Market ETF",
  SPY: "SPDR S&P 500 ETF Trust",
  IVV: "iShares Core S&P 500 ETF",
  IWM: "iShares Russell 2000 ETF",
  IWD: "iShares Russell 1000 Value ETF",
  IWF: "iShares Russell 1000 Growth ETF",
  IWN: "iShares Russell 2000 Value ETF",
  IWO: "iShares Russell 2000 Growth ETF",
  IWY: "iShares Russell Top 200 Growth ETF",
  IJR: "iShares Core S&P Small-Cap ETF",
  IJH: "iShares Core S&P Mid-Cap ETF",
  QQQ: "Invesco QQQ Trust",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  XLK: "Technology Select Sector SPDR Fund",
  XLV: "Health Care Select Sector SPDR Fund",
  XLF: "Financial Select Sector SPDR Fund",
  XLE: "Energy Select Sector SPDR Fund",
  XLI: "Industrial Select Sector SPDR Fund",
  XLY: "Consumer Discretionary Select Sector SPDR Fund",
  XLP: "Consumer Staples Select Sector SPDR Fund",
  XLU: "Utilities Select Sector SPDR Fund",
  XLB: "Materials Select Sector SPDR Fund",
  XLRE: "Real Estate Select Sector SPDR Fund",
  XLC: "Communication Services Select Sector SPDR Fund",
  EFA: "iShares MSCI EAFE ETF",
  EEM: "iShares MSCI Emerging Markets ETF",
  VEA: "Vanguard FTSE Developed Markets ETF",
  VWO: "Vanguard FTSE Emerging Markets ETF",
  AGG: "iShares Core U.S. Aggregate Bond ETF",
  BND: "Vanguard Total Bond Market ETF",
  IEF: "iShares 7-10 Year Treasury Bond ETF",
  TLT: "iShares 20+ Year Treasury Bond ETF",
  SHY: "iShares 1-3 Year Treasury Bond ETF",
  BIL: "SPDR Bloomberg 1-3 Month T-Bill ETF",
  SGOV: "iShares 0-3 Month Treasury Bond ETF",
  LQD: "iShares iBoxx Investment Grade Corporate Bond ETF",
  HYG: "iShares iBoxx High Yield Corporate Bond ETF",
  TIP: "iShares TIPS Bond ETF",
  GLD: "SPDR Gold Shares",
  SLV: "iShares Silver Trust",
  DBC: "Invesco DB Commodity Index Tracking Fund",
  VNQ: "Vanguard Real Estate ETF",
  RSP: "Invesco S&P 500 Equal Weight ETF",
  DGRO: "iShares Core Dividend Growth ETF",
  SCHD: "Schwab U.S. Dividend Equity ETF",
  NOBL: "ProShares S&P 500 Dividend Aristocrats ETF",
  FNDX: "Schwab Fundamental U.S. Large Company ETF",
  AVUV: "Avantis U.S. Small Cap Value ETF",
  DFAC: "Dimensional U.S. Core Equity 2 ETF",
};

export function fundName(ticker: string): string {
  return ETF_NAMES[ticker.trim().toUpperCase()] ?? "";
}
